// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SandStats.Data;

#nullable disable

namespace SandStats.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260728230520_InicialPostgres")]
    partial class InicialPostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SandStats.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("JugadorId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MustResetPassword")
                        .HasColumnType("boolean");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("SandStats.Models.Dupla", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .HasColumnType("text");

                    b.Property<int>("Jugador1Id")
                        .HasColumnType("integer");

                    b.Property<int>("Jugador2Id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Jugador2Id");

                    b.HasIndex("Jugador1Id", "Jugador2Id")
                        .IsUnique()
                        .HasDatabaseName("UX_Dupla_J1_J2");

                    b.ToTable("Duplas");
                });

            modelBuilder.Entity("SandStats.Models.EnVivo.Accion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Calidad")
                        .HasColumnType("integer");

                    b.Property<int>("Complejo")
                        .HasColumnType("integer");

                    b.Property<bool>("EsDe2da")
                        .HasColumnType("boolean");

                    b.Property<bool>("EsRejuego")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Fundamento")
                        .HasColumnType("integer");

                    b.Property<int>("JugadorId")
                        .HasColumnType("integer");

                    b.Property<int>("RallyId")
                        .HasColumnType("integer");

                    b.Property<int>("Secuencia")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("JugadorId");

                    b.HasIndex("RallyId");

                    b.ToTable("Acciones");
                });

            modelBuilder.Entity("SandStats.Models.EnVivo.DetalleAtaque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccionId")
                        .HasColumnType("integer");

                    b.Property<bool>("EsEspecial")
                        .HasColumnType("boolean");

                    b.Property<bool>("EsVarilla")
                        .HasColumnType("boolean");

                    b.Property<int>("Lado")
                        .HasColumnType("integer");

                    b.Property<int>("TipoAccion")
                        .HasColumnType("integer");

                    b.Property<int>("ZonaDestino")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AccionId")
                        .IsUnique();

                    b.ToTable("DetallesAtaque");
                });

            modelBuilder.Entity("SandStats.Models.EnVivo.DetalleRecepcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccionId")
                        .HasColumnType("integer");

                    b.Property<int>("TipoRecepcion")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AccionId")
                        .IsUnique();

                    b.ToTable("DetallesRecepcion");
                });

            modelBuilder.Entity("SandStats.Models.EnVivo.DetalleSaque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccionId")
                        .HasColumnType("integer");

                    b.Property<int>("TipoSaque")
                        .HasColumnType("integer");

                    b.Property<int>("ZonaSaque")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AccionId")
                        .IsUnique();

                    b.ToTable("DetallesSaque");
                });

            modelBuilder.Entity("SandStats.Models.EnVivo.ModificadorCombinada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CalidadCargada")
                        .HasColumnType("integer");

                    b.Property<int?>("CalidadDerivada")
                        .HasColumnType("integer");

                    b.Property<int>("FundamentoCargado")
                        .HasColumnType("integer");

                    b.Property<int>("FundamentoDerivado")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FundamentoCargado", "CalidadCargada", "FundamentoDerivado")
                        .IsUnique()
                        .HasDatabaseName("UX_ModificadorCombinada");

                    b.ToTable("ModificadoresCombinadas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CalidadCargada = 5,
                            CalidadDerivada = 1,
                            FundamentoCargado = 1,
                            FundamentoDerivado = 0
                        },
                        new
                        {
                            Id = 2,
                            CalidadCargada = 4,
                            CalidadDerivada = 1,
                            FundamentoCargado = 1,
                            FundamentoDerivado = 0
                        },
                        new
                        {
                            Id = 3,
                            CalidadCargada = 3,
                            CalidadDerivada = 3,
                            FundamentoCargado = 1,
                            FundamentoDerivado = 0
                        },
                        new
                        {
                            Id = 4,
                            CalidadCargada = 2,
                            CalidadDerivada = 2,
                            FundamentoCargado = 1,
                            FundamentoDerivado = 0
                        },
                        new
                        {
                            Id = 5,
                            CalidadCargada = 1,
                            CalidadDerivada = 4,
                            FundamentoCargado = 1,
                            FundamentoDerivado = 0
                        },
                        new
                        {
                            Id = 6,
                            CalidadCargada = 0,
                            CalidadDerivada = 5,
                            FundamentoCargado = 1,
                            FundamentoDerivado = 0
                        },
                        new
                        {
                            Id = 7,
                            CalidadCargada = 5,
                            CalidadDerivada = 2,
                            FundamentoCargado = 3,
                            FundamentoDerivado = 2
                        },
                        new
                        {
                            Id = 8,
                            CalidadCargada = 4,
                            CalidadDerivada = 1,
                            FundamentoCargado = 3,
                            FundamentoDerivado = 2
                        },
                        new
                        {
                            Id = 9,
                            CalidadCargada = 2,
                            CalidadDerivada = 4,
                            FundamentoCargado = 3,
                            FundamentoDerivado = 2
                        },
                        new
                        {
                            Id = 10,
                            CalidadCargada = 1,
                            CalidadDerivada = 4,
                            FundamentoCargado = 3,
                            FundamentoDerivado = 2
                        },
                        new
                        {
                            Id = 11,
                            CalidadCargada = 0,
                            CalidadDerivada = 5,
                            FundamentoCargado = 3,
                            FundamentoDerivado = 2
                        },
                        new
                        {
                            Id = 12,
                            CalidadCargada = 5,
                            CalidadDerivada = 1,
                            FundamentoCargado = 4,
                            FundamentoDerivado = 2
                        },
                        new
                        {
                            Id = 13,
                            CalidadCargada = 4,
                            CalidadDerivada = 1,
                            FundamentoCargado = 4,
                            FundamentoDerivado = 2
                        },
                        new
                        {
                            Id = 14,
                            CalidadCargada = 3,
                            CalidadDerivada = 4,
                            FundamentoCargado = 4,
                            FundamentoDerivado = 2
                        },
                        new
                        {
                            Id = 15,
                            CalidadCargada = 2,
                            CalidadDerivada = 4,
                            FundamentoCargado = 4,
                            FundamentoDerivado = 2
                        },
                        new
                        {
                            Id = 16,
                            CalidadCargada = 1,
                            CalidadDerivada = 4,
                            FundamentoCargado = 4,
                            FundamentoDerivado = 2
                        },
                        new
                        {
                            Id = 17,
                            CalidadCargada = 0,
                            CalidadDerivada = 5,
                            FundamentoCargado = 4,
                            FundamentoDerivado = 2
                        });
                });

            modelBuilder.Entity("SandStats.Models.EnVivo.PartidoEnVivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Dupla1Id")
                        .HasColumnType("integer");

                    b.Property<int>("Dupla2Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Torneo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Dupla1Id");

                    b.HasIndex("Dupla2Id");

                    b.ToTable("PartidosEnVivo");
                });

            modelBuilder.Entity("SandStats.Models.EnVivo.Rally", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("DuplaGanadoraId")
                        .HasColumnType("integer");

                    b.Property<int>("MarcadorDupla1")
                        .HasColumnType("integer");

                    b.Property<int>("MarcadorDupla2")
                        .HasColumnType("integer");

                    b.Property<int>("NumeroRally")
                        .HasColumnType("integer");

                    b.Property<int>("SetEnVivoId")
                        .HasColumnType("integer");

                    b.Property<int?>("TipoCierre")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DuplaGanadoraId");

                    b.HasIndex("SetEnVivoId");

                    b.ToTable("Rallies");
                });

            modelBuilder.Entity("SandStats.Models.EnVivo.SetEnVivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("DuplaGanadoraId")
                        .HasColumnType("integer");

                    b.Property<int>("DuplaQueSacaPrimeroId")
                        .HasColumnType("integer");

                    b.Property<int>("NumeroSet")
                        .HasColumnType("integer");

                    b.Property<int>("PartidoEnVivoId")
                        .HasColumnType("integer");

                    b.Property<int>("SacadorInicialDupla1JugadorId")
                        .HasColumnType("integer");

                    b.Property<int>("SacadorInicialDupla2JugadorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DuplaGanadoraId");

                    b.HasIndex("DuplaQueSacaPrimeroId");

                    b.HasIndex("PartidoEnVivoId");

                    b.HasIndex("SacadorInicialDupla1JugadorId");

                    b.HasIndex("SacadorInicialDupla2JugadorId");

                    b.ToTable("SetsEnVivo");
                });

            modelBuilder.Entity("SandStats.Models.EstadisticaAtaque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Accion")
                        .HasColumnType("integer");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<int?>("DesdePunto")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCarga")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("JugadorId")
                        .HasColumnType("integer");

                    b.Property<int>("Lado")
                        .HasColumnType("integer");

                    b.Property<int>("PartidoId")
                        .HasColumnType("integer");

                    b.Property<int>("Resultado")
                        .HasColumnType("integer");

                    b.Property<int>("Scope")
                        .HasColumnType("integer");

                    b.Property<int?>("SetNumero")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("JugadorId");

                    b.HasIndex("PartidoId");

                    b.ToTable("EstadisticaAtaque");
                });

            modelBuilder.Entity("SandStats.Models.EstadisticaK2", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Agregados")
                        .HasColumnType("integer");

                    b.Property<int?>("BloqueadoAtqa1")
                        .HasColumnType("integer");

                    b.Property<int?>("BloqueadoAtqa5")
                        .HasColumnType("integer");

                    b.Property<int?>("BloqueadoAtqa6")
                        .HasColumnType("integer");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<int?>("DesdePunto")
                        .HasColumnType("integer");

                    b.Property<int?>("ErroresVarios")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCarga")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Fuente")
                        .HasColumnType("integer");

                    b.Property<int>("JugadorId")
                        .HasColumnType("integer");

                    b.Property<int>("PartidoId")
                        .HasColumnType("integer");

                    b.Property<int>("Resultado")
                        .HasColumnType("integer");

                    b.Property<int>("Scope")
                        .HasColumnType("integer");

                    b.Property<int?>("SetNumero")
                        .HasColumnType("integer");

                    b.Property<int?>("SetsJugados")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("JugadorId");

                    b.HasIndex("PartidoId");

                    b.ToTable("EstadisticaK2");
                });

            modelBuilder.Entity("SandStats.Models.Jugador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Altura")
                        .HasColumnType("integer");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Apodo")
                        .HasColumnType("text");

                    b.Property<int?>("DuplaId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImagenPerfilPath")
                        .HasColumnType("text");

                    b.Property<string>("ManoHabil")
                        .HasColumnType("text");

                    b.Property<string>("Nacionalidad")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Peso")
                        .HasColumnType("integer");

                    b.Property<int>("Posicion")
                        .HasColumnType("integer");

                    b.Property<int>("RolPrincipal")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DuplaId");

                    b.ToTable("Jugadores");
                });

            modelBuilder.Entity("SandStats.Models.JugadorLinks", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("JugadorId")
                        .HasColumnType("integer");

                    b.Property<string>("LinkArmado")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("LinkBloqueo")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("LinkExtra")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("LinkK1")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("LinkK2")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("LinkSaque")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("JugadorId");

                    b.ToTable("JugadorLinks");
                });

            modelBuilder.Entity("SandStats.Models.Partido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Clima")
                        .HasColumnType("integer");

                    b.Property<int>("Dupla1Id")
                        .HasColumnType("integer");

                    b.Property<int>("Dupla2Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("SetsGanadosDupla1")
                        .HasColumnType("integer");

                    b.Property<int>("SetsGanadosDupla2")
                        .HasColumnType("integer");

                    b.Property<string>("Torneo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("Dupla1Id");

                    b.HasIndex("Dupla2Id");

                    b.ToTable("Partidos");
                });

            modelBuilder.Entity("SandStats.Models.SandStats.Models.EstadisticaRecepcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("DesdePunto")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCarga")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("JugadorId")
                        .HasColumnType("integer");

                    b.Property<int>("PartidoId")
                        .HasColumnType("integer");

                    b.Property<int>("ResultadoRecepcion")
                        .HasColumnType("integer");

                    b.Property<int>("Scope")
                        .HasColumnType("integer");

                    b.Property<int?>("SetNumero")
                        .HasColumnType("integer");

                    b.Property<int>("TipoRecepcion")
                        .HasColumnType("integer");

                    b.Property<int>("TipoSaque")
                        .HasColumnType("integer");

                    b.Property<int>("ZonaRecepcion")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("JugadorId");

                    b.HasIndex("PartidoId");

                    b.ToTable("EstadisticaRecepcion");
                });

            modelBuilder.Entity("SandStats.Models.Set", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GanadorDuplaId")
                        .HasColumnType("integer");

                    b.Property<int>("NumeroSet")
                        .HasColumnType("integer");

                    b.Property<int>("PartidoId")
                        .HasColumnType("integer");

                    b.Property<int>("PuntosDupla1")
                        .HasColumnType("integer");

                    b.Property<int>("PuntosDupla2")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GanadorDuplaId");

                    b.HasIndex("PartidoId");

                    b.ToTable("Sets");
                });

            modelBuilder.Entity("SandStats.Models.VideoLinksJugadorPartido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("JugadorId")
                        .HasColumnType("integer");

                    b.Property<string>("LinkK1")
                        .HasColumnType("text");

                    b.Property<string>("LinkK2")
                        .HasColumnType("text");

                    b.Property<string>("LinkSaque")
                        .HasColumnType("text");

                    b.Property<int>("PartidoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("JugadorId");

                    b.HasIndex("PartidoId");

                    b.ToTable("VideoLinksJugadorPartido");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SandStats.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SandStats.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SandStats.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SandStats.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SandStats.Models.Dupla", b =>
                {
                    b.HasOne("SandStats.Models.Jugador", "Jugador1")
                        .WithMany()
                        .HasForeignKey("Jugador1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SandStats.Models.Jugador", "Jugador2")
                        .WithMany()
                        .HasForeignKey("Jugador2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Jugador1");

                    b.Navigation("Jugador2");
                });

            modelBuilder.Entity("SandStats.Models.EnVivo.Accion", b =>
                {
                    b.HasOne("SandStats.Models.Jugador", "Jugador")
                        .WithMany()
                        .HasForeignKey("JugadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SandStats.Models.EnVivo.Rally", "Rally")
                        .WithMany("Acciones")
                        .HasForeignKey("RallyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jugador");

                    b.Navigation("Rally");
                });

            modelBuilder.Entity("SandStats.Models.EnVivo.DetalleAtaque", b =>
                {
                    b.HasOne("SandStats.Models.EnVivo.Accion", "Accion")
                        .WithOne("DetalleAtaque")
                        .HasForeignKey("SandStats.Models.EnVivo.DetalleAtaque", "AccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accion");
                });

            modelBuilder.Entity("SandStats.Models.EnVivo.DetalleRecepcion", b =>
                {
                    b.HasOne("SandStats.Models.EnVivo.Accion", "Accion")
                        .WithOne("DetalleRecepcion")
                        .HasForeignKey("SandStats.Models.EnVivo.DetalleRecepcion", "AccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accion");
                });

            modelBuilder.Entity("SandStats.Models.EnVivo.DetalleSaque", b =>
                {
                    b.HasOne("SandStats.Models.EnVivo.Accion", "Accion")
                        .WithOne("DetalleSaque")
                        .HasForeignKey("SandStats.Models.EnVivo.DetalleSaque", "AccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accion");
                });

            modelBuilder.Entity("SandStats.Models.EnVivo.PartidoEnVivo", b =>
                {
                    b.HasOne("SandStats.Models.Dupla", "Dupla1")
                        .WithMany()
                        .HasForeignKey("Dupla1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SandStats.Models.Dupla", "Dupla2")
                        .WithMany()
                        .HasForeignKey("Dupla2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dupla1");

                    b.Navigation("Dupla2");
                });

            modelBuilder.Entity("SandStats.Models.EnVivo.Rally", b =>
                {
                    b.HasOne("SandStats.Models.Dupla", "DuplaGanadora")
                        .WithMany()
                        .HasForeignKey("DuplaGanadoraId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SandStats.Models.EnVivo.SetEnVivo", "SetEnVivo")
                        .WithMany("Rallies")
                        .HasForeignKey("SetEnVivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DuplaGanadora");

                    b.Navigation("SetEnVivo");
                });

            modelBuilder.Entity("SandStats.Models.EnVivo.SetEnVivo", b =>
                {
                    b.HasOne("SandStats.Models.Dupla", "DuplaGanadora")
                        .WithMany()
                        .HasForeignKey("DuplaGanadoraId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SandStats.Models.Dupla", "DuplaQueSacaPrimero")
                        .WithMany()
                        .HasForeignKey("DuplaQueSacaPrimeroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SandStats.Models.EnVivo.PartidoEnVivo", "PartidoEnVivo")
                        .WithMany("Sets")
                        .HasForeignKey("PartidoEnVivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SandStats.Models.Jugador", "SacadorInicialDupla1Jugador")
                        .WithMany()
                        .HasForeignKey("SacadorInicialDupla1JugadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SandStats.Models.Jugador", "SacadorInicialDupla2Jugador")
                        .WithMany()
                        .HasForeignKey("SacadorInicialDupla2JugadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DuplaGanadora");

                    b.Navigation("DuplaQueSacaPrimero");

                    b.Navigation("PartidoEnVivo");

                    b.Navigation("SacadorInicialDupla1Jugador");

                    b.Navigation("SacadorInicialDupla2Jugador");
                });

            modelBuilder.Entity("SandStats.Models.EstadisticaAtaque", b =>
                {
                    b.HasOne("SandStats.Models.Jugador", "Jugador")
                        .WithMany()
                        .HasForeignKey("JugadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SandStats.Models.Partido", "Partido")
                        .WithMany()
                        .HasForeignKey("PartidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jugador");

                    b.Navigation("Partido");
                });

            modelBuilder.Entity("SandStats.Models.EstadisticaK2", b =>
                {
                    b.HasOne("SandStats.Models.Jugador", "Jugador")
                        .WithMany()
                        .HasForeignKey("JugadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SandStats.Models.Partido", "Partido")
                        .WithMany()
                        .HasForeignKey("PartidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jugador");

                    b.Navigation("Partido");
                });

            modelBuilder.Entity("SandStats.Models.Jugador", b =>
                {
                    b.HasOne("SandStats.Models.Dupla", "Dupla")
                        .WithMany()
                        .HasForeignKey("DuplaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Dupla");
                });

            modelBuilder.Entity("SandStats.Models.JugadorLinks", b =>
                {
                    b.HasOne("SandStats.Models.Jugador", "Jugador")
                        .WithMany()
                        .HasForeignKey("JugadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jugador");
                });

            modelBuilder.Entity("SandStats.Models.Partido", b =>
                {
                    b.HasOne("SandStats.Models.Dupla", "Dupla1")
                        .WithMany()
                        .HasForeignKey("Dupla1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SandStats.Models.Dupla", "Dupla2")
                        .WithMany()
                        .HasForeignKey("Dupla2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dupla1");

                    b.Navigation("Dupla2");
                });

            modelBuilder.Entity("SandStats.Models.SandStats.Models.EstadisticaRecepcion", b =>
                {
                    b.HasOne("SandStats.Models.Jugador", "Jugador")
                        .WithMany()
                        .HasForeignKey("JugadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SandStats.Models.Partido", "Partido")
                        .WithMany()
                        .HasForeignKey("PartidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jugador");

                    b.Navigation("Partido");
                });

            modelBuilder.Entity("SandStats.Models.Set", b =>
                {
                    b.HasOne("SandStats.Models.Dupla", "Ganador")
                        .WithMany()
                        .HasForeignKey("GanadorDuplaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SandStats.Models.Partido", "Partido")
                        .WithMany("Sets")
                        .HasForeignKey("PartidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ganador");

                    b.Navigation("Partido");
                });

            modelBuilder.Entity("SandStats.Models.VideoLinksJugadorPartido", b =>
                {
                    b.HasOne("SandStats.Models.Jugador", "Jugador")
                        .WithMany()
                        .HasForeignKey("JugadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SandStats.Models.Partido", "Partido")
                        .WithMany()
                        .HasForeignKey("PartidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jugador");

                    b.Navigation("Partido");
                });

            modelBuilder.Entity("SandStats.Models.EnVivo.Accion", b =>
                {
                    b.Navigation("DetalleAtaque");

                    b.Navigation("DetalleRecepcion");

                    b.Navigation("DetalleSaque");
                });

            modelBuilder.Entity("SandStats.Models.EnVivo.PartidoEnVivo", b =>
                {
                    b.Navigation("Sets");
                });

            modelBuilder.Entity("SandStats.Models.EnVivo.Rally", b =>
                {
                    b.Navigation("Acciones");
                });

            modelBuilder.Entity("SandStats.Models.EnVivo.SetEnVivo", b =>
                {
                    b.Navigation("Rallies");
                });

            modelBuilder.Entity("SandStats.Models.Partido", b =>
                {
                    b.Navigation("Sets");
                });
#pragma warning restore 612, 618
        }
    }
}
